### ISSUE TITLE
The Joystick setup procedure is partially correct

### ISSUE THREAD

**Issue by Xiaohong-Deng** [autorope/donkeypart_ps3_controller#1]
I used PS4 controller but it should also apply to PS3 controller.

First, `from donkeypart_ps3_controller.part import PS3Joystick`, not `from donkeypart_ps3_controller import PS3Joystick`.

Next

```
ctr = PS3Joystick(
   max_throttle=cfg.JOYSTICK_MAX_THROTTLE,
   steering_scale=cfg.JOYSTICK_STEERING_SCALE,
   throttle_axis=cfg.JOYSTICK_THROTTLE_AXIS,
   auto_record_on_throttle=cfg.AUTO_RECORD_ON_THROTTLE
)
```
It should be `PS3JoystickController` not `PS3Joystick`. It will pass the arguments to the `super`, which is `JoystickController` who doesn't have `max_throttle` and `throttle_axis` as keyword parameters. Simply remove them is fine.

Any reason not adding PS4 controller to `README.md`?  Here is my [Bluetooth setup walkthrough](https://github.com/Xiaohong-Deng/denkeycar/blob/master/controller.md). With Tawn's code for PS4 controller which is in `donkeypart_ps3_controller/part.py`, it works well. I'll be happy if you add my walkthrough to this repo.

**Comment by Ezward** [comment]
This is what I got to work:

```
from donkeypart_ps3_controller.part import PS3JoystickController

...

    if use_joystick or cfg.USE_JOYSTICK_AS_DEFAULT:
        print("Using joystick: ")
        print("    throttle_scale=" + str(cfg.JOYSTICK_MAX_THROTTLE))
        print("    steering_scale=" + str(cfg.JOYSTICK_STEERING_SCALE))
        #print("    throttle_axis=" + str(cfg.JOYSTICK_THROTTLE_AXIS))
        print("    auto_record_on_throttle=" + str(cfg.AUTO_RECORD_ON_THROTTLE))
        #ctr = JoystickController(max_throttle=cfg.JOYSTICK_MAX_THROTTLE,
        #                         steering_scale=cfg.JOYSTICK_STEERING_SCALE,
        #                         throttle_axis=cfg.JOYSTICK_THROTTLE_AXIS,
        #                         auto_record_on_throttle=cfg.AUTO_RECORD_ON_THROTTLE)
        ctr = PS3JoystickController(
            throttle_scale=cfg.JOYSTICK_MAX_THROTTLE,
            steering_scale=cfg.JOYSTICK_STEERING_SCALE,
            #throttle_axis=cfg.JOYSTICK_THROTTLE_AXIS,
            auto_record_on_throttle=cfg.AUTO_RECORD_ON_THROTTLE
        )
    else:
        # This web controller will create a web server that is capable
        # of managing steering, throttle, and modes, and more.
        ctr = LocalWebController(use_chaos=use_chaos)

```

So the PS3JoystickController does not take max_throttle or throttle_axis as arguments.   

Also, I would expect that if we change donkeypart_ps3_controller/__init__.py to import PS3JoystickController rather than PS3Joystick, then we would not need to use the .part when we import into manage.py.  So __init__py becomes:

`from .part import PS3JoystickController
`

**Comment by Ezward** [comment]
I created a pull request with the changes.

**Comment by wroscoe** [comment]
I've merged both of you're pull requests so this should be fixed. Thanks!
